# Generated by Django 6.1.1 on 2026-10-02 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amore', '0003_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del voto')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_registrados', to='amore.question', verbose_name='Pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_api', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto registrado (API)',
                'verbose_name_plural': 'Votos registrados (API)',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'question'), name='un_voto_por_usuario_y_pregunta')],
            },
        ),
    ]
